<?php
/**
 * LeadStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * LeadStatus Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LeadStatus implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LeadStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'lead_status_id' => 'int',
        'lead_status' => 'string',
        'default_status' => 'bool',
        'status_type' => 'int',
        'field_order' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'lead_status_id' => 'int64',
        'lead_status' => null,
        'default_status' => null,
        'status_type' => 'int32',
        'field_order' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'lead_status_id' => 'LEAD_STATUS_ID',
        'lead_status' => 'LEAD_STATUS',
        'default_status' => 'DEFAULT_STATUS',
        'status_type' => 'STATUS_TYPE',
        'field_order' => 'FIELD_ORDER'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'lead_status_id' => 'setLeadStatusId',
        'lead_status' => 'setLeadStatus',
        'default_status' => 'setDefaultStatus',
        'status_type' => 'setStatusType',
        'field_order' => 'setFieldOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'lead_status_id' => 'getLeadStatusId',
        'lead_status' => 'getLeadStatus',
        'default_status' => 'getDefaultStatus',
        'status_type' => 'getStatusType',
        'field_order' => 'getFieldOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['lead_status_id'] = isset($data['lead_status_id']) ? $data['lead_status_id'] : null;
        $this->container['lead_status'] = isset($data['lead_status']) ? $data['lead_status'] : null;
        $this->container['default_status'] = isset($data['default_status']) ? $data['default_status'] : null;
        $this->container['status_type'] = isset($data['status_type']) ? $data['status_type'] : null;
        $this->container['field_order'] = isset($data['field_order']) ? $data['field_order'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['lead_status'] === null) {
            $invalidProperties[] = "'lead_status' can't be null";
        }
        if ((strlen($this->container['lead_status']) > 255)) {
            $invalidProperties[] = "invalid value for 'lead_status', the character length must be smaller than or equal to 255.";
        }

        if ((strlen($this->container['lead_status']) < 0)) {
            $invalidProperties[] = "invalid value for 'lead_status', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['lead_status'] === null) {
            return false;
        }
        if (strlen($this->container['lead_status']) > 255) {
            return false;
        }
        if (strlen($this->container['lead_status']) < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets lead_status_id
     *
     * @return int
     */
    public function getLeadStatusId()
    {
        return $this->container['lead_status_id'];
    }

    /**
     * Sets lead_status_id
     *
     * @param int $lead_status_id lead_status_id
     *
     * @return $this
     */
    public function setLeadStatusId($lead_status_id)
    {
        $this->container['lead_status_id'] = $lead_status_id;

        return $this;
    }

    /**
     * Gets lead_status
     *
     * @return string
     */
    public function getLeadStatus()
    {
        return $this->container['lead_status'];
    }

    /**
     * Sets lead_status
     *
     * @param string $lead_status lead_status
     *
     * @return $this
     */
    public function setLeadStatus($lead_status)
    {
        if ((strlen($lead_status) > 255)) {
            throw new \InvalidArgumentException('invalid length for $lead_status when calling LeadStatus., must be smaller than or equal to 255.');
        }
        if ((strlen($lead_status) < 0)) {
            throw new \InvalidArgumentException('invalid length for $lead_status when calling LeadStatus., must be bigger than or equal to 0.');
        }

        $this->container['lead_status'] = $lead_status;

        return $this;
    }

    /**
     * Gets default_status
     *
     * @return bool
     */
    public function getDefaultStatus()
    {
        return $this->container['default_status'];
    }

    /**
     * Sets default_status
     *
     * @param bool $default_status default_status
     *
     * @return $this
     */
    public function setDefaultStatus($default_status)
    {
        $this->container['default_status'] = $default_status;

        return $this;
    }

    /**
     * Gets status_type
     *
     * @return int
     */
    public function getStatusType()
    {
        return $this->container['status_type'];
    }

    /**
     * Sets status_type
     *
     * @param int $status_type status_type
     *
     * @return $this
     */
    public function setStatusType($status_type)
    {
        $this->container['status_type'] = $status_type;

        return $this;
    }

    /**
     * Gets field_order
     *
     * @return int
     */
    public function getFieldOrder()
    {
        return $this->container['field_order'];
    }

    /**
     * Sets field_order
     *
     * @param int $field_order field_order
     *
     * @return $this
     */
    public function setFieldOrder($field_order)
    {
        $this->container['field_order'] = $field_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


