<?php
/**
 * APIObjectPermissionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * APIObjectPermissionsTest Class Doc Comment
 *
 * @category    Class */
// * @description APIObjectPermissions
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIObjectPermissionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIObjectPermissions"
     */
    public function testAPIObjectPermissions()
    {
    }

    /**
     * Test attribute "object_type"
     */
    public function testPropertyObjectType()
    {
    }

    /**
     * Test attribute "permissions_state"
     */
    public function testPropertyPermissionsState()
    {
    }

    /**
     * Test attribute "can_read"
     */
    public function testPropertyCanRead()
    {
    }

    /**
     * Test attribute "can_create"
     */
    public function testPropertyCanCreate()
    {
    }

    /**
     * Test attribute "can_edit"
     */
    public function testPropertyCanEdit()
    {
    }

    /**
     * Test attribute "can_delete"
     */
    public function testPropertyCanDelete()
    {
    }
}
