<?php
/**
 * APITaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * APITaskTest Class Doc Comment
 *
 * @category    Class */
// * @description APITask
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APITaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "APITask"
     */
    public function testAPITask()
    {

    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {

    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {

    }

    /**
     * Test attribute "completed_date_utc"
     */
    public function testPropertyCompletedDateUtc()
    {

    }

    /**
     * Test attribute "publicly_visible"
     */
    public function testPropertyPubliclyVisible()
    {

    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {

    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {

    }

    /**
     * Test attribute "opportunity_id"
     */
    public function testPropertyOpportunityId()
    {

    }

    /**
     * Test attribute "milestone_id"
     */
    public function testPropertyMilestoneId()
    {

    }

    /**
     * Test attribute "pipeline_id"
     */
    public function testPropertyPipelineId()
    {

    }

    /**
     * Test attribute "stage_id"
     */
    public function testPropertyStageId()
    {

    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "percent_complete"
     */
    public function testPropertyPercentComplete()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "assigned_by_user_id"
     */
    public function testPropertyAssignedByUserId()
    {

    }

    /**
     * Test attribute "parent_task_id"
     */
    public function testPropertyParentTaskId()
    {

    }

    /**
     * Test attribute "owner_visible"
     */
    public function testPropertyOwnerVisible()
    {

    }

    /**
     * Test attribute "responsible_user_id"
     */
    public function testPropertyResponsibleUserId()
    {

    }

    /**
     * Test attribute "assigned_team_id"
     */
    public function testPropertyAssignedTeamId()
    {

    }

    /**
     * Test attribute "assigned_date_utc"
     */
    public function testPropertyAssignedDateUtc()
    {

    }

    /**
     * Test attribute "owner_user_id"
     */
    public function testPropertyOwnerUserId()
    {

    }

    /**
     * Test attribute "date_created_utc"
     */
    public function testPropertyDateCreatedUtc()
    {

    }

    /**
     * Test attribute "date_updated_utc"
     */
    public function testPropertyDateUpdatedUtc()
    {

    }

    /**
     * Test attribute "reminder_date_utc"
     */
    public function testPropertyReminderDateUtc()
    {

    }

    /**
     * Test attribute "reminder_sent"
     */
    public function testPropertyReminderSent()
    {

    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {

    }

    /**
     * Test attribute "tasklinks"
     */
    public function testPropertyTasklinks()
    {

    }

    /**
     * Test attribute "can_edit"
     */
    public function testPropertyCanEdit()
    {

    }

    /**
     * Test attribute "can_delete"
     */
    public function testPropertyCanDelete()
    {

    }

}
