<?php
/**
 * NoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NoteTest Class Doc Comment
 *
 * @category    Class */
// * @description Note
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NoteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Note"
     */
    public function testNote()
    {

    }

    /**
     * Test attribute "note_id"
     */
    public function testPropertyNoteId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {

    }

    /**
     * Test attribute "link_subject_id"
     */
    public function testPropertyLinkSubjectId()
    {

    }

    /**
     * Test attribute "link_subject_type"
     */
    public function testPropertyLinkSubjectType()
    {

    }

    /**
     * Test attribute "owner_user_id"
     */
    public function testPropertyOwnerUserId()
    {

    }

    /**
     * Test attribute "date_created_utc"
     */
    public function testPropertyDateCreatedUtc()
    {

    }

    /**
     * Test attribute "date_updated_utc"
     */
    public function testPropertyDateUpdatedUtc()
    {

    }

    /**
     * Test attribute "visible_to"
     */
    public function testPropertyVisibleTo()
    {

    }

    /**
     * Test attribute "visible_team_id"
     */
    public function testPropertyVisibleTeamId()
    {

    }

    /**
     * Test attribute "visible_user_ids"
     */
    public function testPropertyVisibleUserIds()
    {

    }

    /**
     * Test attribute "notelinks"
     */
    public function testPropertyNotelinks()
    {

    }

    /**
     * Test attribute "can_edit"
     */
    public function testPropertyCanEdit()
    {

    }

    /**
     * Test attribute "can_delete"
     */
    public function testPropertyCanDelete()
    {

    }

}
