<?php
/**
 * ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addActivitySetAssignment
     *
     * Adds an Activity Set to a Contact.
     *
     */
    public function testAddActivitySetAssignment()
    {
    }

    /**
     * Test case for addDate
     *
     * Adds a Date.
     *
     */
    public function testAddDate()
    {
    }

    /**
     * Test case for addEntity
     *
     * Adds a Contact.
     *
     */
    public function testAddEntity()
    {
    }

    /**
     * Test case for addFileAttachment
     *
     * Adds a File Attachment to a Contact.
     *
     */
    public function testAddFileAttachment()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following a Contact.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addLink
     *
     * Adds a Link.
     *
     */
    public function testAddLink()
    {
    }

    /**
     * Test case for addNotes
     *
     * Adds a Note to a Contact.
     *
     */
    public function testAddNotes()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a Tag.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for deleteDate
     *
     * Deletes a Date.
     *
     */
    public function testDeleteDate()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes a Contact.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Contact.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteImage
     *
     * Deletes a Contact's Image.
     *
     */
    public function testDeleteImage()
    {
    }

    /**
     * Test case for deleteLink
     *
     * Deletes a Link.
     *
     */
    public function testDeleteLink()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a Tag.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for getEmails
     *
     * Gets a list of a Contact's Emails.
     *
     */
    public function testGetEmails()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Contacts.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Contacts.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntitiesByTag
     *
     * Gets a list of Contacts filtered by tags.
     *
     */
    public function testGetEntitiesByTag()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets a Contact.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getEvents
     *
     * Gets a Contact's Events.
     *
     */
    public function testGetEvents()
    {
    }

    /**
     * Test case for getFileAttachments
     *
     * Gets a Contact's File Attachments.
     *
     */
    public function testGetFileAttachments()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for a Contact.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getImage
     *
     * Gets a Contact's Image.
     *
     */
    public function testGetImage()
    {
    }

    /**
     * Test case for getLinks
     *
     * Gets a Contact's Links.
     *
     */
    public function testGetLinks()
    {
    }

    /**
     * Test case for getNotes
     *
     * Gets a Contact's Notes.
     *
     */
    public function testGetNotes()
    {
    }

    /**
     * Test case for getTasks
     *
     * Gets a list of a Contact's Tasks.
     *
     */
    public function testGetTasks()
    {
    }

    /**
     * Test case for updateDate
     *
     * Updates a Date.
     *
     */
    public function testUpdateDate()
    {
    }

    /**
     * Test case for updateEntity
     *
     * Updates a Contact.
     *
     */
    public function testUpdateEntity()
    {
    }

    /**
     * Test case for updateImage
     *
     * Updates a Contact's Image.
     *
     */
    public function testUpdateImage()
    {
    }

    /**
     * Test case for updateLink
     *
     * Updates a Link.
     *
     */
    public function testUpdateLink()
    {
    }

    /**
     * Test case for updateNotes
     *
     * Updates a note of a Contact.
     *
     */
    public function testUpdateNotes()
    {
    }
}
