<?php
/**
 * EmailsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EmailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addComment
     *
     * Adds a Comment to an Email.
     *
     */
    public function testAddComment()
    {
    }

    /**
     * Test case for addFollow
     *
     * Start following an Email.
     *
     */
    public function testAddFollow()
    {
    }

    /**
     * Test case for addLink
     *
     * Adds a Link.
     *
     */
    public function testAddLink()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a Tag.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for deleteEntity
     *
     * Deletes an Email.
     *
     */
    public function testDeleteEntity()
    {
    }

    /**
     * Test case for deleteFollow
     *
     * Stop following an Email.
     *
     */
    public function testDeleteFollow()
    {
    }

    /**
     * Test case for deleteLink
     *
     * Deletes a Link.
     *
     */
    public function testDeleteLink()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a Tag.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for getComments
     *
     * Gets an Email's Comments.
     *
     */
    public function testGetComments()
    {
    }

    /**
     * Test case for getEntities
     *
     * Gets a list of Emails.
     *
     */
    public function testGetEntities()
    {
    }

    /**
     * Test case for getEntitiesBySearch
     *
     * Gets a filtered list of Emails.
     *
     */
    public function testGetEntitiesBySearch()
    {
    }

    /**
     * Test case for getEntitiesByTag
     *
     * Gets a list of Emails filtered by tags.
     *
     */
    public function testGetEntitiesByTag()
    {
    }

    /**
     * Test case for getEntity
     *
     * Gets an Email.
     *
     */
    public function testGetEntity()
    {
    }

    /**
     * Test case for getFileAttachments
     *
     * Gets an Email's File Attachments.
     *
     */
    public function testGetFileAttachments()
    {
    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow state for an Email.
     *
     */
    public function testGetFollow()
    {
    }

    /**
     * Test case for getLinks
     *
     * Gets an Email's Links.
     *
     */
    public function testGetLinks()
    {
    }
}
