<?php
/**
 * LeadStatusesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LeadStatusesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LeadStatusesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLeadStatus
     *
     * Adds a Lead Status.
     *
     */
    public function testAddLeadStatus()
    {
    }

    /**
     * Test case for deleteLeadStatus
     *
     * Deletes a Lead Status.
     *
     */
    public function testDeleteLeadStatus()
    {
    }

    /**
     * Test case for getLeadStatuses
     *
     * Gets a list of Lead Statuses.
     *
     */
    public function testGetLeadStatuses()
    {
    }

    /**
     * Test case for updateLeadStatus
     *
     * Updates a Lead Status.
     *
     */
    public function testUpdateLeadStatus()
    {
    }
}
