<?php
/**
 * NotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addComment
     *
     * Adds a Comment to a Note.
     *
     */
    public function testAddComment()
    {

    }

    /**
     * Test case for addFileAttachment
     *
     * Adds a File Attachment to a Note.
     *
     */
    public function testAddFileAttachment()
    {

    }

    /**
     * Test case for addFollow
     *
     * Start following a Note.
     *
     */
    public function testAddFollow()
    {

    }

    /**
     * Test case for addNoteLink
     *
     * Adds a Note Link.
     *
     */
    public function testAddNoteLink()
    {

    }

    /**
     * Test case for deleteFollow
     *
     * Stop following a Note.
     *
     */
    public function testDeleteFollow()
    {

    }

    /**
     * Test case for deleteNote
     *
     * Deletes a Note.
     *
     */
    public function testDeleteNote()
    {

    }

    /**
     * Test case for deleteNoteLink
     *
     * Deletes a Note Link.
     *
     */
    public function testDeleteNoteLink()
    {

    }

    /**
     * Test case for getComments
     *
     * Gets a Note's Comments.
     *
     */
    public function testGetComments()
    {

    }

    /**
     * Test case for getFileAttachments
     *
     * Gets a Note's File Attachments.
     *
     */
    public function testGetFileAttachments()
    {

    }

    /**
     * Test case for getFollow
     *
     * Gets a Follow record for the Note.
     *
     */
    public function testGetFollow()
    {

    }

    /**
     * Test case for getNote
     *
     * Gets a Note.
     *
     */
    public function testGetNote()
    {

    }

    /**
     * Test case for getNotes
     *
     * Gets a list of Notes..
     *
     */
    public function testGetNotes()
    {

    }

    /**
     * Test case for getNotesBySearch
     *
     * Gets a filtered list of Notes..
     *
     */
    public function testGetNotesBySearch()
    {

    }

    /**
     * Test case for updateNote
     *
     * Updates a Note.
     *
     */
    public function testUpdateNote()
    {

    }

}
